exports.dummyData = [
  {
    _id: 0,
    profileName: 'wolfebyte',
    profilePic: '/img/wbyte.png',
    profileMood: 'cloudy',
    profileMoodEmoji: ';)',
    profileStatus: ':-)',
    profileGender: 'Male',
    profileAge: '30',
    profileCity: 'Arvada',
    profileState: 'COLORADO',
    profileCountry: 'United States',
    profileLogin: '4/20/2020',
    urlAddress: '/wolfebyte',
    interestsGeneral: 'internet, doggies, etc.',
    interestsMusic: 'rock n roll asian fusion',
    interestsMovies: 'muppets treasure island',
    interestsTelevision: 'cheers',
    interestsBooks: 'what is books',
    interestsHeroes: 'the rock aka dawayan johnston',
    detailsStatus: 'swexy',
    detailsHereFor: 'lasagna',
    detailsHometown: 'hawkins, in',
    detailsZodiacSign: 'i guess so',
    detailsSmokeDrink: '69',
    detailsOccupation: 'keepin it breezy',
    headline: 'ready to party rock',
    blogPosts: [
      [4, 'approving comments ...', ''],
      [3, 'new homepage look', ''],
      [2, 'whats going on with friend counts?', ''],
      [1, 'extended network', ''],
      [0, 'am i online?', ''],
    ],
    blurbsAboutMe: 'a blue-skinned humanoid who wears a purple hood over his bare-bone skull.',
    blurbsWhoIdLikeToMeet: 'your mom',
    friends: [
      [4, 1],
      [2, 0],
      [3, 0],
      [9, 0],
      [1, 0],
      [5, 0],
      [6, 0],
      [7, 0],
      [8, 0],
      [10, 1],
    ],
    comments: [
      [['clifford', '/img/wbyte.png', 3], 'Sep 21 2008 5:26P', 'hey ding dong'],
      [['snoopy', '/img/wbyte.png', 2], 'Oct 1 2007 1:46A', 'shhhh'],
      [['airbud returns', '/img/wbyte.png', 10], 'Nov 3 2005 6:56P', 'woof'],
    ],
  },
  {
    _id: 1,
    profileName: 'clifford',
    profilePic: 'https://static01.nyt.com/images/2018/05/17/arts/television/17clifford-item/17clifford-item-articleLarge.jpg?quality=75&auto=webp&disable=upscale',
    profileMood: 'woof',
    profileMoodEmoji: ':P',
    profileStatus: 'im red',
    profileGender: 'Male',
    profileAge: '12',
    profileCity: 'Seattle',
    profileState: 'WASHINGTON',
    profileCountry: 'United States',
    profileLogin: '5/23/2021',
    urlAddress: '/clifford',
    interestsGeneral: 'being big and being a dog',
    interestsMusic: 'music is great',
    interestsMovies: '101 dalmatians',
    interestsTelevision: 'tv is cool',
    interestsBooks: 'wow books',
    interestsHeroes: 'other big dogs',
    detailsStatus: 'here for a good time',
    detailsHereFor: 'status is chillin',
    detailsHometown: 'seattle',
    detailsZodiacSign: 'doggy',
    detailsSmokeDrink: 'both',
    detailsOccupation: 'being a big dog',
    headline: 'woof woof woof woof',
    blogPosts: [
      ['crazy night', ''],
      ['sup', ''],
    ],
    blurbsAboutMe: 'im clifford, dumbass',
    blurbsWhoIdLikeToMeet: 'charlie from charlie brown',
    friends: [
      [1, 0],
      [2, 0],
      [3, 0],
      [4, 0],
      [5, 0],
      [6, 0],
    ],
    comments: [
      [['clifford', '/img/wbyte.png', 3], 'Sep 21 2008 5:26P', 'fahrk'],
      [['snoopy', '/img/wbyte.png', 2], 'Oct 1 2007 1:46A', 'stop it now please ok'],
      [['airbud returns', '/img/wbyte.png', 10], 'Nov 3 2005 6:56P', 'slam dunk it'],
    ],
  },
];

// exports.dummyData = JSON.stringify(data);
