exports.dummyData = [
  {
    _id: 0,
    email: 'wolfebyte.net@gmail.com',
    password: 'hotdog',
    description: {
      name: 'wolfebyte',
      pic: '/img/wbyte.png',
      mood: 'cloudy',
      moodEmoji: ';)',
      status: ':-)',
      gender: 'Male',
      age: '30',
      city: 'Arvada',
      state: 'COLORADO',
      country: 'United States',
      login: '4/20/2020',
    },
    urlAddress: '/wolfebyte',
    interests: {
      general: 'internet, doggies, etc.',
      music: 'rock n roll asian fusion',
      movies: 'muppets treasure island',
      television: 'cheers',
      books: 'what is books',
      heroes: 'the rock aka dawayan johnston',
    },
    details: {
      status: 'swexy',
      hereFor: 'lasagna',
      hometown: 'hawkins, in',
      zodiacSign: 'i guess so',
      smokeDrink: '69',
      occupation: 'keepin it breezy',
    },
    headline: 'ready to party rock',
    postedPosts: [
      {
        _id: 6,
        title: 'what else',
        content: 'were not friends so dont text my parents anymore',
      },
      {
        _id: 5,
        title: 'just because',
        content: 'i hate you.',
      },
      {
        _id: 4,
        title: 'i could use some help',
        content: 'just kidding i hate you',
      },
      {
        _id: 3,
        title: 'further discussion',
        content: 'dont forget i know everything',
      },
      {
        _id: 2,
        title: 'what what what what what what what what what what what what what what what what what what what what what what what what what what what what what what what what what what what what what what what what what what what what what what what what what what what what what what',
        content: 'ah fuhck, i believe you have done me wrong.',
      },
      {
        _id: 1,
        title: 'excellent',
        content: 'i will shoot forth the lasers from my eyeballs',
      },
      {
        _id: 0,
        title: 'ok guys',
        content: 'stop it',
      },
    ],
    blurbs: {
      aboutMe: 'a blue-skinned humanoid who wears a purple hood over his bare-bone skull.',
      whoIdLikeToMeet: 'your mom',
    },
    friends: [
      [9, 1, 3],
      [8, 0, 2],
      [7, 0, 1],
      [6, 0, 4],
      [5, 0, 5],
      [4, 0, 6],
      [3, 0, 7],
      [2, 0],
      [1, 0],
      [0, 1, 8],
    ],
    comments: [
      [2, 0, 'Sep 21 2008 5:26P', 'fahrk'],
      [1, 1, 'Oct 1 2007 1:46A', 'stop it now please ok'],
      [0, 1, 'Nov 3 2005 6:56P', 'slam dunk it'],
    ],
  },
  {
    _id: 1,
    email: 'cliff.dawg@gmail.com',
    password: 'dipshit',
    description: {
      name: 'clifford',
      pic: 'https://static01.nyt.com/images/2018/05/17/arts/television/17clifford-item/17clifford-item-articleLarge.jpg?quality=75&auto=webp&disable=upscale',
      mood: 'woof',
      moodEmoji: ':P',
      status: 'im red',
      gender: 'Male',
      age: '12',
      city: 'Seattle',
      state: 'WASHINGTON',
      country: 'United States',
      login: '5/23/2021',
    },
    urlAddress: '/clifford',
    interests: {
      general: 'being big and being a dog',
      music: 'music is great',
      movies: '101 dalmatians',
      television: 'tv is cool',
      books: 'wow books',
      heroes: 'other big dogs',
    },
    details: {
      status: 'here for a good time',
      hereFor: 'status is chillin',
      hometown: 'seattle',
      zodiacSign: 'doggy',
      smokeDrink: 'both',
      occupation: 'being a big dog',
    },
    headline: 'woof woof woof woof',
    postedPosts: [
      {
        _id: 2,
        title: 'wow thats a big hot dog',
        content: 'its of the casper variety i suppose, but one could argue that. im not sure if the absolute quantity of remaining sausage is enough for your mom to fit in her mouth. so dont forget that and keep a visual of it in your mind when you go to sleep at night. if this is long enough i can stop typing and just see if this example fits in the stupid column or not but whatever its just part of what i do and typing is a hoot.',
      },
      {
        _id: 1,
        title: 'crazy night',
        content: 'chess board am i right',
      },
      {
        _id: 0,
        title: 'sup',
        content: 'stop it',
      },
    ],
    blurbs: {
      aboutMe: 'im clifford, dumbass',
      whoIdLikeToMeet: 'charlie from charlie brown',
    },
    friends: [
      [0, 0],
      [1, 0],
      [2, 0],
      [3, 0],
      [4, 0],
      [5, 0],
    ],
    comments: [
      [2, 0, 'Sep 21 2008 5:26P', 'fahrk'],
      [1, 0, 'Oct 1 2007 1:46A', 'stop it now please ok'],
    ],
  },
];

// exports.dummyData = JSON.stringify(data);
